apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-proxy
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5672
      protocol: TCP
  selector:
    name: rabbitmq